name: Publish

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - run: yarn install
      - run: NODE_OPTIONS=--openssl-legacy-provider yarn build
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
